workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Fix Info.plist
        script: |
          # إنشاء Info.plist صحيح
          cat > ios/Runner/Info.plist << 'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
          	<key>CFBundleDevelopmentRegion</key>
          	<string>$(DEVELOPMENT_LANGUAGE)</string>
          	<key>CFBundleDisplayName</key>
          	<string>Habibui Ios</string>
          	<key>CFBundleExecutable</key>
          	<string>$(EXECUTABLE_NAME)</string>
          	<key>CFBundleIdentifier</key>
          	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
          	<key>CFBundleInfoDictionaryVersion</key>
          	<string>6.0</string>
          	<key>CFBundleName</key>
          	<string>habibuios</string>
          	<key>CFBundlePackageType</key>
          	<string>APPL</string>
          	<key>CFBundleShortVersionString</key>
          	<string>$(FLUTTER_BUILD_NAME)</string>
          	<key>CFBundleSignature</key>
          	<string>????</string>
          	<key>CFBundleVersion</key>
          	<string>$(FLUTTER_BUILD_NUMBER)</string>
          	<key>LSRequiresIPhoneOS</key>
          	<true/>
          	<key>UILaunchStoryboardName</key>
          	<string>LaunchScreen</string>
          	<key>UIMainStoryboardFile</key>
          	<string>Main</string>
          	<key>UISupportedInterfaceOrientations</key>
          	<array>
          		<string>UIInterfaceOrientationPortrait</string>
          		<string>UIInterfaceOrientationLandscapeLeft</string>
          		<string>UIInterfaceOrientationLandscapeRight</string>
          	</array>
          	<key>UISupportedInterfaceOrientations~ipad</key>
          	<array>
          		<string>UIInterfaceOrientationPortrait</string>
          		<string>UIInterfaceOrientationPortraitUpsideDown</string>
          		<string>UIInterfaceOrientationLandscapeLeft</string>
          		<string>UIInterfaceOrientationLandscapeRight</string>
          	</array>
          	<key>UIViewControllerBasedStatusBarAppearance</key>
          	<false/>
          	<key>CADisableMinimumFrameDurationOnPhone</key>
          	<true/>
          	<key>UIApplicationSupportsIndirectInputEvents</key>
          	<true/>
          </dict>
          </plist>
          EOF

      - name: Fix AppDelegate
        script: |
          # إصلاح AppDelegate.swift
          sed -i '' 's/@UIApplicationMain/@main/g' ios/Runner/AppDelegate.swift
          sed -i '' 's/class AppDelegate: FlutterAppDelegate/class AppDelegate: FlutterAppDelegate/g' ios/Runner/AppDelegate.swift

      - name: Fix gitignore
        script: |
          # إضافة Swift Package Manager directories إلى .gitignore
          echo "" >> .gitignore
          echo "# Swift Package Manager" >> .gitignore
          echo ".build/" >> .gitignore
          echo "DerivedData/" >> .gitignore
          echo "*.xcworkspace" >> .gitignore

      - name: Fix iOS Deployment Target
        script: |
          # إصلاح iOS Deployment Target في جميع ملفات المشروع
          find . -name "*.pbxproj" -exec sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = [^;]*/IPHONEOS_DEPLOYMENT_TARGET = 12.0/g' {} \;
          find . -name "*.pbxproj" -exec sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET=[^;]*/IPHONEOS_DEPLOYMENT_TARGET=12.0/g' {} \;
            
          # إصلاح Podfile
          sed -i '' "s/platform :ios, '[^']*'/platform :ios, '12.0'/g" ios/Podfile
            
          # إصلاح AppFrameworkInfo.plist
          /usr/libexec/PlistBuddy -c "Set :MinimumOSVersion 12.0" ios/Flutter/AppFrameworkInfo.plist || true
      

      - name: Validate Info.plist
        script: |
          plutil -lint ios/Runner/Info.plist
          echo "Info.plist validation complete"

      

      - name: Clean and install pods
        script: |
          cd ios
          rm -rf Pods
          rm -f Podfile.lock
          pod install

      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign

    artifacts:
      - build/ios/iphoneos/Runner.app