flutter_application_path = '../'


require File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

platform :ios, '13.0'
use_frameworks!

target 'Runner' do
  flutter_install_all_ios_pods(flutter_application_path)
end